<a href="https://colab.research.google.com/github/Lyxthor/ML-Practice-Sem-4/blob/main/minggu-3_4/BasicPreprocessingMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([
    [2.1, -1.9, 5.5],
    [-1.5, 2.4, 3.5],
    [5.9, 2.3, -5.8]
])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 5.9,  2.3, -5.8]])

# **Binarization Method**
mengkonversi nilai yang lebih besar dari threshold ke nila 1 dan yang lebih kecil ke nilai 0

In [3]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarized_data = preprocessor.transform(sample_data)
binarized_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 0.]])

# **Scaling Method**


In [4]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0 ,1))
# **
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
# scaled_data = preprocessor.fit_transform(sample_data) **For short
scaled_data

array([[0.48648649, 0.        , 1.        ],
       [0.        , 1.        , 0.82300885],
       [1.        , 0.97674419, 0.        ]])

# **Normalization Method**


# **L1 Normalization : Least Absolute Deviations**
Ref : https://en.wikipedia.org/w/index.php?title=Least_absolute_deviations&oldid=1258886998

In [5]:
l1_normalized_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalized_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.42142857,  0.16428571, -0.41428571]])

# **L2 Normalization : Least Squares**
Ref : https://en.wikipedia.org/wiki/Least_squares


In [6]:
l2_normalized_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalized_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.68706914,  0.26784051, -0.6754239 ]])